services:
    iobroker:
        restart: always
        image: buanet/iobroker:latest-v9
        container_name: iobroker
        hostname: iobroker
        ports:
            - "8081:8081"
            - "9229:9229"
            - "9222:9222"
            - "9191:9191"
            - "9192:9192"
        volumes:
            - iobrokerdata:/opt/iobroker

    sqlserver:
        restart: always
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver
        hostname: sqlserver
        ports:
            - "1433:1433"
        environment:
            MSSQL_SA_PASSWORD: "io!Broker123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        volumes:
            - sqldata:/var/opt/mssql

volumes:
    iobrokerdata:
    sqldata:
