/*global systemDictionary:true */
"use strict";

systemDictionary = {
	"klf200 adapter settings": {
		en: "klf200 adapter settings",
		de: "klf200 Adaptereinstellungen",
		ru: "настройки адаптера klf200",
		pt: "configurações do adaptador klf200",
		nl: "klf200 adapterinstellingen",
		fr: "paramètres de l'adaptateur klf200",
		it: "impostazioni dell'adattatore klf200",
		es: "ajustes del adaptador klf200",
		pl: "ustawienia adaptera klf200",
		"zh-cn": "klf200适配器设置",
	},
	host: {
		en: "host",
		de: "Host",
		ru: "хозяин",
		pt: "hospedeiro",
		nl: "gastheer",
		fr: "hôte",
		it: "ospite",
		es: "anfitrión",
		pl: "gospodarz",
		"zh-cn": "主办",
	},
	password: {
		en: "password",
		de: "Passwort",
		ru: "пароль",
		pt: "senha",
		nl: "wachtwoord",
		fr: "mot de passe",
		it: "parola d'ordine",
		es: "contraseña",
		pl: "hasło",
		"zh-cn": "密码",
	},
	"on save adapter restarts with new config immediately": {
		en: "on save adapter restarts with new config immediately",
		de: "Beim Speichern wird der Adapter sofort mit der neuen Konfiguration neu gestartet",
		ru: "при сохранении адаптер перезапускается с новым конфигом немедленно",
		pt: "ao salvar o adaptador reinicia imediatamente com a nova configuração",
		nl: "bij het opslaan van adapter wordt onmiddellijk opnieuw opgestart met nieuwe configuratie",
		fr: "lors de l'enregistrement, l'adaptateur redémarre avec la nouvelle configuration immédiatement",
		it: "on save adapter si riavvia immediatamente con la nuova configurazione",
		es: "al guardar el adaptador se reinicia con la nueva configuración inmediatamente",
		pl: "po zapisaniu adapter natychmiast uruchamia się ponownie z nową konfiguracją",
		"zh-cn": "保存适配器上的适配器立即以新配置重新启动",
	},
};
