/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "KLF-200 adapter settings": {                    "en": "KLF-200 adapter settings",                        "de": "Einstellungen des KLF-200 Adapters",              "ru": "Настройки адаптера KLF-200",                      "pt": "Configurações do adaptador KLF-200",              "nl": "KLF-200 adapterinstellingen",                     "fr": "Paramètres de l'adaptateur KLF-200",              "it": "Impostazioni dell'adattatore KLF-200",            "es": "Configuraciones del adaptador KLF-200",           "pl": "Ustawienia adaptera KLF-200"},
    "host": {                                        "en": "Host",                                            "de": "Host",                                            "ru": "хозяин",                                          "pt": "Hospedeiro",                                      "nl": "Gastheer",                                        "fr": "Hôte",                                            "it": "Ospite",                                          "es": "Anfitrión",                                       "pl": "Gospodarz"},
    "on save adapter restarts with new config immediately": {"en": "On save the adapter restarts with new configuration immediately", "de": "Beim Speichern von Einstellungen wird der Adapter sofort neu gestartet.", "ru": "При перезагрузке адаптер перезагружается с новой конфигурацией немедленно", "pt": "Ao salvar, o adaptador é reiniciado com a nova configuração imediatamente", "nl": "Bij opslaan wordt de adapter onmiddellijk opnieuw opgestart met een nieuwe configuratie", "fr": "A l'enregistrement, l'adaptateur redémarre immédiatement avec la nouvelle configuration", "it": "Al salvataggio, l'adattatore si riavvia immediatamente con la nuova configurazione", "es": "Al guardar, el adaptador se reinicia con una nueva configuración de inmediato", "pl": "Po zapisaniu adapter natychmiast uruchamia się ponownie z nową konfiguracją"},
    "password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło"},
    "pollInterval": {                                "en": "Polling interval in minutes",                     "de": "Abfragehäufigkeit in Minuten",                    "ru": "Интервал опроса в минутах",                       "pt": "Intervalo de pesquisa em minutos",                "nl": "Polling-interval in minuten",                     "fr": "Intervalle d'interrogation en minutes",           "it": "Intervallo di polling in minuti",                 "es": "Intervalo de sondeo en minutos",                  "pl": "Interwał odpytywania w minutach"},
};